### ISSUE TITLE
Create a reusable bar chart

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#22]
It will be used for energy charts for Pendulum Lab, Masses & Springs and Energy Skate Park: Basics (and maybe other sims in the future!)

UPDATE: balancing-chemical-equations also has bar charts

**Comment by samreid** [comment]
We googled for terminology, and it seems like bar chart and bar graph are technically interchangeable, but it seems that "bar chart" wins the popular vote.

**Comment by Denz1994** [comment]
## **Points to consider**

**BarNode:**
- bar object with {property, labelNode, fill, stroke}


**GraphNode:**
- Allow for negative representations of bar values, with a legend instead of label nodes on the x-axis.
- Consider a horizontal orientation.
- Derived length of x-axis based on the number of bars passed in

**Comment by samreid** [comment]
@Denz1994 and I discussed API and strategy for this and created a scaffolding.  I'll leave the next steps up to you @Denz1994 but let me know if you want to discuss it further.

**Comment by Denz1994** [comment]
Closing this issue because a common code bar chart and bar node has been created.
