### ISSUE TITLE
What is an "invalid" bar?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#36]
While working on #35 I was reviewing BarNode.update and I don't understand what constitutes an "invalid" bar. There is a line of documentation that says the bar is invalid when there is "one negative with multiple values". Perhaps this is sim specific, but I don't understand the case yet.

@Denz1994 could you please explain?

**Comment by Denz1994** [comment]
Invalid bars are `BarNodes` with entries that contain negative values. This is useful for composite barNodes (barNodes with multiple entries). If a composite bar node contains a negative value the color is changed (`options.invalidBarColor`) and only the first entry is used to show the range.

This naming convention "invalid bar" was chosen for future cases where a bar node may be considered invalid other than just containing a negative value. Alternatively, this could be changed to "negativeBar" or "conatinsNegativeEntry". Whatever the alteration to the name, it should indicate that something special needs to be done to this bar because of its value.

This could use better documentation in its current state and I've updated some doc. Could you take a look in `BarNode.js`?

**Comment by jessegreenberg** [comment]
Thanks so much @Denz1994 , the documentation you added really helps clarify and I understand now. Thanks!
