### ISSUE TITLE
Generalize ChartCursor

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#42]
Neuron has a "ChartCursor" which the user can grab and drag move back and forth through time. The same cursor is needed in energy-skate-park so I would like to generalize this component.

![image](https://user-images.githubusercontent.com/6396244/59322231-41064a80-8ca3-11e9-83c4-b6047afe49df.png)
 

@jbphet do you have thoughts or recommendations about this since you are the author of ChartCursor?

Since this is related to the "chart" I opened this issue in griddle, which is where I think the component should live.

**Comment by jessegreenberg** [comment]
It seems like we could just move the cursor graphic to griddle or we could generalize more of the functionality of the cursor. If we generalize the functionality of the cursor, we probably will want to generalize portions of the time chart too since the cursor is pretty coupled with the chart. I think that would be the best way to go so I am going to look into that.

**Comment by jbphet** [comment]
I don't have a ton of thoughts on this, since I did it quite a while ago, but I have one idea on how to improve it.  I have noticed that people tend to miss this feature, and that seems like a shame, because it's very cool and adds a lot to the sim.  I think the cursor itself should highlight noticeably when the mouse goes over it so that users are more likely to notice it and try it out.

**Comment by jessegreenberg** [comment]
OK, that sounds good, thanks!

**Comment by samreid** [comment]
This was developed in griddle for Energy Skate Park, and we can port other sims to use it as necessary, closing.
