### ISSUE TITLE
GridNode API for setLineSpacings

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#62]
In https://github.com/phetsims/griddle/issues/59 we determined that you should be able to specify multiple line spacings at once since there are interdependencies.  However, the existing API leads to usage sites like:

```js
this.setLineSpacings( null, null, null, ( this.gridHeight - 1 ) / gridRange );
```

Would this be easier to read as a named config?

```js
this.setLineSpacings({
  minorHorizontalLineSpacing: ( this.gridHeight - 1 ) / gridRange
});
```

**Comment by samreid** [comment]
Or how about `setHorizontalLineSpacings` + `setVerticalLineSpacings`, each with 2 required arguments?

**Comment by samreid** [comment]
Also, if the minor lines are constrained to line up with the major lines, would a superior API be to specify `numberOfMinorTicksPerMajor` or equivalent, so that it automatically divides equally?

**Comment by jessegreenberg** [comment]
> Or how about setHorizontalLineSpacings + setVerticalLineSpacings, each with 2 required arguments

This was considered in https://github.com/phetsims/scenery-phet/issues/601, but since it is important to require that at least one spacing is defined across horizontal and vertical it is important to specify all at once.

> if the minor lines are constrained to line up with the major lines, would a superior API be to specify numberOfMinorTicksPerMajor

In my opinion this is more inconvenient. Very often the spacing will be in model coordinates, and it seems the client would have to calculate `numberOfMinorTicksPerMajor` themselves.

> Would this be easier to read as a named config

I really like this, I will try it out!

**Comment by jessegreenberg** [comment]
OK I used a config for this and updated sites. @samreid would you like to review?

**Comment by samreid** [comment]
I reviewed the commits and they look very nice, thanks!  Closing.
